repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: mixed-line-ending
    - id: check-merge-conflict
    - id: check-symlinks
    - id: check-executables-have-shebangs
    - id: check-json
    - id: check-yaml
    - id: check-toml

- repo: https://github.com/asottile/pyupgrade
  rev: v1.25.1
  hooks:
    - id: pyupgrade
      args: [--py36-plus]

- repo: https://github.com/asottile/seed-isort-config
  rev: v1.9.2
  hooks:
    - id: seed-isort-config
      args: [--exclude=tests/.*\.py, --application-directories=src/]

- repo: https://github.com/timothycrosley/isort
  rev: 4.3.21
  hooks:
    - id: isort
      additional_dependencies: ["isort[pyproject]"]

- repo: local
  hooks:
    - id: poetry-export
      name: Export requirements.txt
      entry: poetry export -f requirements.txt -o requirements.txt
      pass_filenames: false
      language: system
    - id: safety
      name: safety check
      entry: poetry run safety check --full-report -r requirements.txt
      pass_filenames: false
      language: system
    - id: remove-requirements
      name: Remove requirements.txt
      entry: rm requirements.txt
      pass_filenames: false
      language: system
    - id: pyt
      name: pyt check
      entry: poetry run python -m pyt
      language: system
      types: [python]
      exclude: ^tests/

- repo: https://github.com/PyCQA/bandit
  rev: 1.6.2
  hooks:
    - id: bandit
      args: [--verbose, --ini, .banditrc, -ll, --recursive, src/]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 'v0.740'
  hooks:
    - id: mypy

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
    - id: debug-statements
    - id: name-tests-test
    - id: check-docstring-first
    - id: flake8
      additional_dependencies: [flake8-bugbear]

- repo: https://github.com/psf/black
  rev: 19.3b0
  hooks:
    - id: black
